"""Flow protocol used by handlers to keep aiogram separate from rendering."""

from __future__ import annotations

from typing import Protocol

from aiogram.types import CallbackQuery, Message


class BotFlow(Protocol):
    async def start(self, message: Message) -> None: ...
    async def catalog(self, message: Message) -> None: ...
    async def compare(self, message: Message, query: str) -> None: ...
    async def shortlist(self, message: Message) -> None: ...
    async def admission(self, message: Message, query: str = "") -> None: ...
    async def digest(self, message: Message) -> None: ...
    async def callback(self, callback: CallbackQuery, data: object) -> None: ...


__all__ = ["BotFlow"]
