/* Generated by scripts/generate-api.mjs. Do not edit. */

export interface paths {
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["list_programs_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program */
        get: operations["get_program_programs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/curriculum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Curriculum */
        get: operations["get_curriculum_programs__id__curriculum_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/admissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program Admissions */
        get: operations["get_program_admissions_programs__id__admissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/admission-fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Program Admission Fit */
        post: operations["calculate_program_admission_fit_programs__id__admission_fit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discipline-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Discipline Areas */
        get: operations["list_discipline_areas_discipline_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proftest/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Questions */
        get: operations["get_questions_proftest_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proftest/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_proftest_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proftest/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Results */
        post: operations["results_proftest_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proftest/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_proftest_profile_get"];
        /** Update Profile */
        put: operations["update_profile_proftest_profile_put"];
        /** Create Profile */
        post: operations["create_profile_proftest_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Recommendations */
        get: operations["current_recommendations_recommendations_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityCode
         * @description Activity dimensions used by deterministic profile matching.
         * @enum {string}
         */
        ActivityCode: "analytical" | "software_creation" | "system_design" | "research" | "physical_engineering" | "communication" | "creative" | "business" | "data";
        /** AdaptiveAnswerResponse */
        AdaptiveAnswerResponse: {
            /** Questionid */
            questionId: string;
            /** Optionid */
            optionId: string;
            /** Dimension */
            dimension: string;
        };
        /** AdaptiveDimensionResponse */
        AdaptiveDimensionResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Spread */
            spread: string;
            /** Significance */
            significance: string;
        };
        /** AdaptiveSelectionResponse */
        AdaptiveSelectionResponse: {
            status: components["schemas"]["AdaptiveStatus"];
            /** Reason */
            reason?: string | null;
            /** Candidatecount */
            candidateCount: number;
            /** Topcandidatecount */
            topCandidateCount: number;
            /** Dimensions */
            dimensions: components["schemas"]["AdaptiveDimensionResponse"][];
        };
        /**
         * AdaptiveStatus
         * @enum {string}
         */
        AdaptiveStatus: "ready" | "skipped";
        /** AdmissionFitBreakdownResponse */
        AdmissionFitBreakdownResponse: {
            minimumReadiness: components["schemas"]["AdmissionFitMetricResponse"];
            passingReadiness: components["schemas"]["AdmissionFitMetricResponse"];
            dataCompleteness: components["schemas"]["AdmissionFitMetricResponse"];
        };
        /**
         * AdmissionFitDataQuality
         * @enum {string}
         */
        AdmissionFitDataQuality: "complete" | "partial" | "unavailable";
        /** AdmissionFitMetricResponse */
        AdmissionFitMetricResponse: {
            /** Value */
            value?: string | null;
            status: components["schemas"]["AdmissionFitMetricStatus"];
        };
        /**
         * AdmissionFitMetricStatus
         * @enum {string}
         */
        AdmissionFitMetricStatus: "available" | "partial" | "not_available";
        /**
         * AdmissionFitReasonKind
         * @enum {string}
         */
        AdmissionFitReasonKind: "fit" | "anti_fit" | "data_gap";
        /** AdmissionFitReasonResponse */
        AdmissionFitReasonResponse: {
            kind: components["schemas"]["AdmissionFitReasonKind"];
            /** Message */
            message: string;
            /** Subject */
            subject?: string | null;
            /** Applicantscore */
            applicantScore?: string | null;
            /** Applicanttotalscore */
            applicantTotalScore?: string | null;
            /** Referencescore */
            referenceScore?: string | null;
            /** Sourcename */
            sourceName?: string | null;
            /**
             * Provenance
             * @default []
             */
            provenance: components["schemas"]["AdmissionProvenanceResponse"][];
        };
        /** AdmissionFitRequestBody */
        AdmissionFitRequestBody: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
            /** Offeringid */
            offeringId: string;
            applicant: components["schemas"]["ApplicantAdmissionProfileRequest"];
        };
        /** AdmissionFitResponse */
        AdmissionFitResponse: {
            /** Programid */
            programId: string;
            /** Offeringid */
            offeringId: string;
            /** Admissionyear */
            admissionYear: number;
            studyForm?: components["schemas"]["StudyForm"] | null;
            fundingType?: components["schemas"]["FundingType"] | null;
            status: components["schemas"]["AdmissionFitStatus"];
            /** Score */
            score: number;
            /** Applicanttotalscore */
            applicantTotalScore?: string | null;
            dataQuality: components["schemas"]["AdmissionFitDataQuality"];
            breakdown: components["schemas"]["AdmissionFitBreakdownResponse"];
            /** Reasons */
            reasons: components["schemas"]["AdmissionFitReasonResponse"][];
            /** Antireasons */
            antiReasons: components["schemas"]["AdmissionFitReasonResponse"][];
            /** Datagaps */
            dataGaps: components["schemas"]["AdmissionFitReasonResponse"][];
        };
        /**
         * AdmissionFitStatus
         * @enum {string}
         */
        AdmissionFitStatus: "realistic" | "borderline" | "unlikely" | "insufficient_data";
        /** AdmissionOfferingResponse */
        AdmissionOfferingResponse: {
            /** Id */
            id: string;
            /** Admissionyear */
            admissionYear: number;
            studyForm?: components["schemas"]["StudyForm"] | null;
            fundingType?: components["schemas"]["FundingType"] | null;
            scope: components["schemas"]["AdmissionScope"];
            /** Places */
            places?: number | null;
            /** Exams */
            exams: components["schemas"]["ExamRequirementResponse"][];
            /** Quotas */
            quotas: components["schemas"]["QuotaResponse"][];
            /** Passingscores */
            passingScores: components["schemas"]["PassingScoreResponse"][];
            /** Tuition */
            tuition: components["schemas"]["TuitionCostResponse"][];
            /** Provenance */
            provenance: components["schemas"]["AdmissionProvenanceResponse"][];
        };
        /** AdmissionProvenanceResponse */
        AdmissionProvenanceResponse: {
            /** Sourcekind */
            sourceKind: string;
            /**
             * Sourceurl
             * Format: uri
             */
            sourceUrl: string;
            /**
             * Capturedat
             * Format: date-time
             */
            capturedAt: string;
            /** Contentsha256 */
            contentSha256: string;
            /** Locator */
            locator?: string | null;
            /** Sourcename */
            sourceName?: string | null;
        };
        /**
         * AdmissionScope
         * @enum {string}
         */
        AdmissionScope: "program" | "direction";
        /** AntiInterestResponse */
        "AntiInterestResponse-Input": {
            area: components["schemas"]["DisciplineAreaCode"];
            /** Intensity */
            intensity: number | string;
        };
        /** AntiInterestResponse */
        "AntiInterestResponse-Output": {
            area: components["schemas"]["DisciplineAreaCode"];
            /** Intensity */
            intensity: string;
        };
        /** ApplicantAdmissionProfileRequest */
        ApplicantAdmissionProfileRequest: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
            /** Scores */
            scores?: components["schemas"]["ApplicantSubjectScoreRequest"][];
        };
        /** ApplicantSubjectScoreRequest */
        ApplicantSubjectScoreRequest: {
            /** Subject */
            subject: string;
            /** Score */
            score: number | string;
        };
        /**
         * AssessmentType
         * @enum {string}
         */
        AssessmentType: "exam" | "credit" | "graded_credit" | "coursework" | "course_project" | "state_exam";
        /**
         * CompareStatus
         * @enum {string}
         */
        CompareStatus: "both" | "only_a" | "only_b" | "different";
        /** ComparisonBlockResponse */
        ComparisonBlockResponse: {
            /** Name */
            name: string;
            totalsA: components["schemas"]["ComparisonTotalsResponse"];
            totalsB: components["schemas"]["ComparisonTotalsResponse"];
            /** Hoursdelta */
            hoursDelta: number;
            /** Creditsdelta */
            creditsDelta: string;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            programA: components["schemas"]["ProgramSummaryResponse"];
            programB: components["schemas"]["ProgramSummaryResponse"];
            scope: components["schemas"]["ComparisonScope"];
            /** Semester */
            semester?: number | null;
            /** Rows */
            rows: components["schemas"]["ComparisonRowResponse"][];
            totalsA: components["schemas"]["ComparisonTotalsResponse"];
            totalsB: components["schemas"]["ComparisonTotalsResponse"];
            /** Blocks */
            blocks: components["schemas"]["ComparisonBlockResponse"][];
            /**
             * Areabreakdowna
             * @default []
             */
            areaBreakdownA: components["schemas"]["DisciplineAreaSummaryResponse"][];
            /**
             * Areabreakdownb
             * @default []
             */
            areaBreakdownB: components["schemas"]["DisciplineAreaSummaryResponse"][];
        };
        /** ComparisonRowResponse */
        ComparisonRowResponse: {
            discipline: components["schemas"]["DisciplineResponse"];
            /** Semester */
            semester?: number | null;
            /** Subjectgroup */
            subjectGroup?: string | null;
            a?: components["schemas"]["WorkloadResponse"] | null;
            b?: components["schemas"]["WorkloadResponse"] | null;
            status: components["schemas"]["CompareStatus"];
            /** Hoursdelta */
            hoursDelta?: number | null;
            /** Creditsdelta */
            creditsDelta?: string | null;
        };
        /**
         * ComparisonScope
         * @enum {string}
         */
        ComparisonScope: "all" | "semester";
        /** ComparisonTotalsResponse */
        ComparisonTotalsResponse: {
            /** Hours */
            hours: number;
            /** Credits */
            credits: string;
        };
        /** ConfidenceResponse */
        "ConfidenceResponse-Input": {
            /** Value */
            value: number | string;
            /** Answeredbase */
            answeredBase: number;
            /** Answeredadaptive */
            answeredAdaptive: number;
        };
        /** ConfidenceResponse */
        "ConfidenceResponse-Output": {
            /** Value */
            value: string;
            /** Answeredbase */
            answeredBase: number;
            /** Answeredadaptive */
            answeredAdaptive: number;
        };
        /** CurriculumItemResponse */
        CurriculumItemResponse: {
            /** Id */
            id: string;
            discipline: components["schemas"]["DisciplineResponse"];
            /** Sourcename */
            sourceName: string;
            /** Semester */
            semester?: number | null;
            /** Hours */
            hours: number;
            /** Credits */
            credits?: string | null;
            /** Assessmenttypes */
            assessmentTypes?: components["schemas"]["AssessmentType"][] | null;
            /** Subjectgroup */
            subjectGroup?: string | null;
            /** Sourceposition */
            sourcePosition?: number | null;
        };
        /** CurriculumResponse */
        CurriculumResponse: {
            program: components["schemas"]["ProgramSummaryResponse"];
            /** Curriculumid */
            curriculumId: string;
            /** Educationyear */
            educationYear: number;
            /**
             * Sourceurl
             * Format: uri
             */
            sourceUrl: string;
            /**
             * Capturedat
             * Format: date-time
             */
            capturedAt: string;
            /** Items */
            items: components["schemas"]["CurriculumItemResponse"][];
        };
        /** DisciplineAreaCatalogResponse */
        DisciplineAreaCatalogResponse: {
            /** Items */
            items: components["schemas"]["DisciplineAreaDefinition"][];
        };
        /**
         * DisciplineAreaCode
         * @enum {string}
         */
        DisciplineAreaCode: "mathematics_statistics" | "computer_science_data" | "physics_astronomy" | "chemistry_materials" | "biology_biotechnology" | "earth_environment" | "engineering_technology" | "architecture_construction" | "agriculture_veterinary" | "medicine_health" | "psychology_cognitive" | "society_social_sciences" | "economics_finance" | "business_management" | "law_policy_public_administration" | "languages_linguistics_literature" | "history_philosophy_humanities" | "art_design_media" | "education_pedagogy" | "sport_tourism_hospitality" | "safety_defense_transport" | "universal_interdisciplinary";
        /** DisciplineAreaDefinition */
        DisciplineAreaDefinition: {
            code: components["schemas"]["DisciplineAreaCode"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Position */
            position: number;
        };
        /** DisciplineAreaResponse */
        DisciplineAreaResponse: {
            code: components["schemas"]["DisciplineAreaCode"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Weight */
            weight: string;
        };
        /** DisciplineAreaSummaryResponse */
        DisciplineAreaSummaryResponse: {
            area: components["schemas"]["DisciplineAreaCode"];
            /** Name */
            name: string;
            /** Share */
            share: string;
        };
        /** DisciplineResponse */
        DisciplineResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Normalizedname */
            normalizedName: string;
            /** Areaweights */
            areaWeights: components["schemas"]["DisciplineAreaResponse"][];
            primaryArea: components["schemas"]["DisciplineAreaCode"];
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "NOT_FOUND" | "CONFLICT" | "SOURCE_CONTRACT_ERROR" | "CONTRACT_ERROR" | "INTERNAL_ERROR";
        /** ErrorDetail */
        ErrorDetail: {
            /** Path */
            path: string;
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["ErrorDetail"][];
        };
        /** EventDetailResponse */
        EventDetailResponse: {
            event: components["schemas"]["EventResponse"];
        };
        /**
         * EventFormat
         * @enum {string}
         */
        EventFormat: "offline" | "online" | "hybrid";
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "additional_education" | "open_day" | "lecture" | "competition" | "career" | "other";
        /** EventListResponse */
        EventListResponse: {
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["EventResponse"][];
            /** Total */
            total: number;
        };
        /** EventProvenanceResponse */
        EventProvenanceResponse: {
            kind: components["schemas"]["SourceKind"];
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Capturedat
             * Format: date-time
             */
            capturedAt: string;
            /** Contentsha256 */
            contentSha256: string;
            /** Locator */
            locator?: string | null;
        };
        /** EventResponse */
        EventResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            kind: components["schemas"]["EventKind"];
            format: components["schemas"]["EventFormat"];
            /**
             * Startsat
             * Format: date-time
             */
            startsAt: string;
            /** Endsat */
            endsAt?: string | null;
            /** Description */
            description?: string | null;
            /** Registrationurl */
            registrationUrl?: string | null;
            /** Universityids */
            universityIds: string[];
            /**
             * Departmentids
             * @default []
             */
            departmentIds: string[];
            /**
             * Programids
             * @default []
             */
            programIds: string[];
            venue?: components["schemas"]["VenueResponse"] | null;
            /** Provenance */
            provenance: components["schemas"]["EventProvenanceResponse"][];
        };
        /** ExamRequirementResponse */
        ExamRequirementResponse: {
            /** Subject */
            subject: string;
            /** Sourcename */
            sourceName: string;
            /** Minimumscore */
            minimumScore?: string | null;
            /** Ischoice */
            isChoice: boolean;
            /** Isrequired */
            isRequired: boolean;
            provenance: components["schemas"]["AdmissionProvenanceResponse"];
        };
        /**
         * FundingType
         * @enum {string}
         */
        FundingType: "budget" | "paid" | "targeted" | "unknown";
        /** MatchScoreResponse */
        MatchScoreResponse: {
            /** Programid */
            programId: string;
            /** Programcode */
            programCode: string;
            /** Contentfit */
            contentFit: number;
            breakdown: components["schemas"]["ScoreBreakdownResponse"];
        };
        /** OptionalMetricResponse */
        OptionalMetricResponse: {
            /** Status */
            status: string;
            /** Value */
            value?: number | null;
        };
        /** PassingScoreResponse */
        PassingScoreResponse: {
            scoreType: components["schemas"]["PassingScoreType"];
            /** Score */
            score: string;
            provenance: components["schemas"]["AdmissionProvenanceResponse"];
        };
        /**
         * PassingScoreType
         * @enum {string}
         */
        PassingScoreType: "budget" | "paid" | "average" | "other";
        /** PreviewCandidateResponse */
        PreviewCandidateResponse: {
            /** Programid */
            programId: string;
            /** Programcode */
            programCode: string;
            /** Contentfit */
            contentFit: number;
        };
        /** ProftestAdaptiveAnswerRequest */
        ProftestAdaptiveAnswerRequest: {
            /** Questionid */
            questionId: string;
            /** Optionid */
            optionId: string;
            /** Dimension */
            dimension: string;
        };
        /** ProftestAnswerRequest */
        ProftestAnswerRequest: {
            /** Questionid */
            questionId: string;
            /** Optionids */
            optionIds: string[];
            /** Intensity */
            intensity?: (number | string) | null;
        };
        /** ProftestPreviewResponse */
        ProftestPreviewResponse: {
            profile: components["schemas"]["UserProfileResponse-Output"];
            adaptive: components["schemas"]["AdaptiveSelectionResponse"];
            question?: components["schemas"]["QuestionResponse"] | null;
            /** Candidates */
            candidates: components["schemas"]["PreviewCandidateResponse"][];
        };
        /** ProftestResultsResponse */
        ProftestResultsResponse: {
            profile: components["schemas"]["UserProfileResponse-Output"];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationResponse"][];
        };
        /** ProftestSubmissionRequest */
        ProftestSubmissionRequest: {
            /** Answers */
            answers?: components["schemas"]["ProftestAnswerRequest"][];
            /** Adaptiveanswers */
            adaptiveAnswers?: components["schemas"]["ProftestAdaptiveAnswerRequest"][];
        };
        /** ProgramAdmissionsResponse */
        ProgramAdmissionsResponse: {
            program: components["schemas"]["ProgramSummaryResponse"];
            /** Programid */
            programId: string;
            /** Offerings */
            offerings: components["schemas"]["AdmissionOfferingResponse"][];
        };
        /** ProgramListResponse */
        ProgramListResponse: {
            /** Items */
            items: components["schemas"]["ProgramSummaryResponse"][];
        };
        /** ProgramResponse */
        ProgramResponse: {
            program: components["schemas"]["ProgramSummaryResponse"];
        };
        /** ProgramSummaryResponse */
        ProgramSummaryResponse: {
            /** Id */
            id: string;
            /** Directionid */
            directionId: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Educationyear */
            educationYear: number;
            /**
             * Studyplanurl
             * Format: uri
             */
            studyPlanUrl: string;
            /**
             * Sourceurl
             * Format: uri
             */
            sourceUrl: string;
        };
        /**
         * QuestionBlock
         * @enum {string}
         */
        QuestionBlock: "interests" | "activities" | "anti_interests" | "adaptive";
        /** QuestionOptionResponse */
        QuestionOptionResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** QuestionResponse */
        QuestionResponse: {
            /** Id */
            id: string;
            block: components["schemas"]["QuestionBlock"];
            /** Prompt */
            prompt: string;
            /** Options */
            options: components["schemas"]["QuestionOptionResponse"][];
            /** Required */
            required: boolean;
            /** Adaptive */
            adaptive: boolean;
            /** Multiselect */
            multiSelect: boolean;
            /** Maxselected */
            maxSelected: number;
        };
        /** QuestionnaireResponse */
        QuestionnaireResponse: {
            /**
             * Version
             * @constant
             */
            version: 1;
            /** Questions */
            questions: components["schemas"]["QuestionResponse"][];
        };
        /** QuotaResponse */
        QuotaResponse: {
            quotaType: components["schemas"]["QuotaType"];
            /** Sourcename */
            sourceName: string;
            /** Places */
            places: number;
            provenance: components["schemas"]["AdmissionProvenanceResponse"];
        };
        /**
         * QuotaType
         * @enum {string}
         */
        QuotaType: "special" | "separate" | "targeted" | "other";
        /**
         * ReasonKind
         * @enum {string}
         */
        ReasonKind: "fit" | "anti_fit";
        /** ReasonResponse */
        ReasonResponse: {
            kind: components["schemas"]["ReasonKind"];
            area?: components["schemas"]["DisciplineAreaCode"] | null;
            activity?: components["schemas"]["ActivityCode"] | null;
            /** Text */
            text: string;
            /** Workload */
            workload: string;
            /** Share */
            share: string;
            /** Sourcenames */
            sourceNames: string[];
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            profile: components["schemas"]["UserProfileResponse-Input"];
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Programid */
            programId: string;
            /** Programcode */
            programCode: string;
            /** Programname */
            programName: string;
            /** Contentfit */
            contentFit: number;
            score: components["schemas"]["MatchScoreResponse"];
            /** Reasons */
            reasons: components["schemas"]["ReasonResponse"][];
            /** Antifitreasons */
            antiFitReasons: components["schemas"]["ReasonResponse"][];
            /** Areashare */
            areaShare: {
                [key: string]: string;
            };
            /** Subjectgroupshare */
            subjectGroupShare: {
                [key: string]: string;
            };
            /** Semesterdistribution */
            semesterDistribution: {
                [key: string]: string;
            };
            /** Distinctivesubjects */
            distinctiveSubjects: string[];
            workloadReadiness: components["schemas"]["OptionalMetricResponse"];
            careerFit: components["schemas"]["OptionalMetricResponse"];
            admissionFit: components["schemas"]["OptionalMetricResponse"];
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            profile: components["schemas"]["UserProfileResponse-Output"];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationResponse"][];
        };
        /** ScoreBreakdownResponse */
        ScoreBreakdownResponse: {
            /** Subjectfit */
            subjectFit: string;
            /** Activityfit */
            activityFit: string;
            /** Distinctivefit */
            distinctiveFit: string;
            /** Antipenalty */
            antiPenalty: string;
            /** Rawcontentfit */
            rawContentFit: string;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "bmstu_common" | "bmstu_major_catalog" | "bmstu_major_detail" | "bmstu_curriculum_document" | "bmstu_events";
        /**
         * StudyForm
         * @enum {string}
         */
        StudyForm: "full_time" | "part_time" | "evening" | "online" | "unknown";
        /** TuitionCostResponse */
        TuitionCostResponse: {
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Academicyear */
            academicYear?: string | null;
            /** Period */
            period?: string | null;
            studyForm?: components["schemas"]["StudyForm"] | null;
            /** Isdiscounted */
            isDiscounted: boolean;
            provenance: components["schemas"]["AdmissionProvenanceResponse"];
        };
        /** UserProfileCreateRequest */
        UserProfileCreateRequest: {
            profile: components["schemas"]["UserProfileResponse-Input"];
        };
        /** UserProfileResponse */
        "UserProfileResponse-Input": {
            /**
             * Version
             * @constant
             */
            version: 1;
            /** Interests */
            interests: components["schemas"]["DisciplineAreaCode"][];
            /** Activitypreferences */
            activityPreferences: components["schemas"]["ActivityCode"][];
            /** Antiinterests */
            antiInterests: components["schemas"]["AntiInterestResponse-Input"][];
            /** Preferredsubjectweights */
            preferredSubjectWeights: {
                [key: string]: number | string;
            };
            /** Preferredactivityweights */
            preferredActivityWeights: {
                [key: string]: number | string;
            };
            /** Negativeweights */
            negativeWeights: {
                [key: string]: number | string;
            };
            confidence: components["schemas"]["ConfidenceResponse-Input"];
            /** Adaptiveanswers */
            adaptiveAnswers: components["schemas"]["AdaptiveAnswerResponse"][];
        };
        /** UserProfileResponse */
        "UserProfileResponse-Output": {
            /**
             * Version
             * @constant
             */
            version: 1;
            /** Interests */
            interests: components["schemas"]["DisciplineAreaCode"][];
            /** Activitypreferences */
            activityPreferences: components["schemas"]["ActivityCode"][];
            /** Antiinterests */
            antiInterests: components["schemas"]["AntiInterestResponse-Output"][];
            /** Preferredsubjectweights */
            preferredSubjectWeights: {
                [key: string]: string;
            };
            /** Preferredactivityweights */
            preferredActivityWeights: {
                [key: string]: string;
            };
            /** Negativeweights */
            negativeWeights: {
                [key: string]: string;
            };
            confidence: components["schemas"]["ConfidenceResponse-Output"];
            /** Adaptiveanswers */
            adaptiveAnswers: components["schemas"]["AdaptiveAnswerResponse"][];
        };
        /** UserProfileSnapshotResponse */
        UserProfileSnapshotResponse: {
            /** Profileid */
            profileId: string;
            profile: components["schemas"]["UserProfileResponse-Output"];
            /** Revision */
            revision: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
        };
        /** UserProfileUpdateRequest */
        UserProfileUpdateRequest: {
            profile: components["schemas"]["UserProfileResponse-Input"];
            /** Expectedrevision */
            expectedRevision: number;
        };
        /** VenueResponse */
        VenueResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** Latitude */
            latitude?: string | null;
            /** Longitude */
            longitude?: string | null;
        };
        /** WorkloadResponse */
        WorkloadResponse: {
            /** Semester */
            semester?: number | null;
            /** Hours */
            hours: number;
            /** Credits */
            credits?: string | null;
            /** Assessmenttypes */
            assessmentTypes?: components["schemas"]["AssessmentType"][] | null;
            /** Subjectgroup */
            subjectGroup?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_programs_programs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_program_programs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_curriculum_programs__id__curriculum_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_program_admissions_programs__id__admissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramAdmissionsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculate_program_admission_fit_programs__id__admission_fit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdmissionFitRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionFitResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_discipline_areas_discipline_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisciplineAreaCatalogResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_compare_get: {
        parameters: {
            query: {
                programIds: string;
                scope?: components["schemas"]["ComparisonScope"];
                semester?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_questions_proftest_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionnaireResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_proftest_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProftestSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProftestPreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    results_proftest_results_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProftestSubmissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProftestResultsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile_proftest_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileSnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_profile_proftest_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileSnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_profile_proftest_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileSnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommend_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    current_recommendations_recommendations_current_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                kind?: components["schemas"]["EventKind"] | null;
                format?: components["schemas"]["EventFormat"] | null;
                universityId?: string | null;
                departmentId?: string | null;
                programId?: string | null;
                recommended?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
