/* Generated by scripts/generate-api.mjs. Do not edit. */

export interface paths {
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["list_programs_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program */
        get: operations["get_program_programs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{id}/curriculum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Curriculum */
        get: operations["get_curriculum_programs__id__curriculum_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discipline-areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Discipline Areas */
        get: operations["list_discipline_areas_discipline_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssessmentType
         * @enum {string}
         */
        AssessmentType: "exam" | "credit" | "graded_credit" | "coursework" | "course_project" | "state_exam";
        /**
         * CompareStatus
         * @enum {string}
         */
        CompareStatus: "both" | "only_a" | "only_b" | "different";
        /** ComparisonBlockResponse */
        ComparisonBlockResponse: {
            /** Name */
            name: string;
            totalsA: components["schemas"]["ComparisonTotalsResponse"];
            totalsB: components["schemas"]["ComparisonTotalsResponse"];
            /** Hoursdelta */
            hoursDelta: number;
            /** Creditsdelta */
            creditsDelta: string;
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            programA: components["schemas"]["ProgramSummaryResponse"];
            programB: components["schemas"]["ProgramSummaryResponse"];
            scope: components["schemas"]["ComparisonScope"];
            /** Semester */
            semester?: number | null;
            /** Rows */
            rows: components["schemas"]["ComparisonRowResponse"][];
            totalsA: components["schemas"]["ComparisonTotalsResponse"];
            totalsB: components["schemas"]["ComparisonTotalsResponse"];
            /** Blocks */
            blocks: components["schemas"]["ComparisonBlockResponse"][];
            /**
             * Areabreakdowna
             * @default []
             */
            areaBreakdownA: components["schemas"]["DisciplineAreaSummaryResponse"][];
            /**
             * Areabreakdownb
             * @default []
             */
            areaBreakdownB: components["schemas"]["DisciplineAreaSummaryResponse"][];
        };
        /** ComparisonRowResponse */
        ComparisonRowResponse: {
            discipline: components["schemas"]["DisciplineResponse"];
            /** Semester */
            semester?: number | null;
            /** Subjectgroup */
            subjectGroup?: string | null;
            a?: components["schemas"]["WorkloadResponse"] | null;
            b?: components["schemas"]["WorkloadResponse"] | null;
            status: components["schemas"]["CompareStatus"];
            /** Hoursdelta */
            hoursDelta?: number | null;
            /** Creditsdelta */
            creditsDelta?: string | null;
        };
        /**
         * ComparisonScope
         * @enum {string}
         */
        ComparisonScope: "all" | "semester";
        /** ComparisonTotalsResponse */
        ComparisonTotalsResponse: {
            /** Hours */
            hours: number;
            /** Credits */
            credits: string;
        };
        /** CurriculumItemResponse */
        CurriculumItemResponse: {
            /** Id */
            id: string;
            discipline: components["schemas"]["DisciplineResponse"];
            /** Sourcename */
            sourceName: string;
            /** Semester */
            semester?: number | null;
            /** Hours */
            hours: number;
            /** Credits */
            credits?: string | null;
            /** Assessmenttypes */
            assessmentTypes?: components["schemas"]["AssessmentType"][] | null;
            /** Subjectgroup */
            subjectGroup?: string | null;
            /** Sourceposition */
            sourcePosition?: number | null;
        };
        /** CurriculumResponse */
        CurriculumResponse: {
            program: components["schemas"]["ProgramSummaryResponse"];
            /** Curriculumid */
            curriculumId: string;
            /** Educationyear */
            educationYear: number;
            /**
             * Sourceurl
             * Format: uri
             */
            sourceUrl: string;
            /**
             * Capturedat
             * Format: date-time
             */
            capturedAt: string;
            /** Items */
            items: components["schemas"]["CurriculumItemResponse"][];
        };
        /** DisciplineAreaCatalogResponse */
        DisciplineAreaCatalogResponse: {
            /** Items */
            items: components["schemas"]["DisciplineAreaDefinition"][];
        };
        /**
         * DisciplineAreaCode
         * @enum {string}
         */
        DisciplineAreaCode: "mathematics_statistics" | "computer_science_data" | "physics_astronomy" | "chemistry_materials" | "biology_biotechnology" | "earth_environment" | "engineering_technology" | "architecture_construction" | "agriculture_veterinary" | "medicine_health" | "psychology_cognitive" | "society_social_sciences" | "economics_finance" | "business_management" | "law_policy_public_administration" | "languages_linguistics_literature" | "history_philosophy_humanities" | "art_design_media" | "education_pedagogy" | "sport_tourism_hospitality" | "safety_defense_transport" | "universal_interdisciplinary";
        /** DisciplineAreaDefinition */
        DisciplineAreaDefinition: {
            code: components["schemas"]["DisciplineAreaCode"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Position */
            position: number;
        };
        /** DisciplineAreaResponse */
        DisciplineAreaResponse: {
            code: components["schemas"]["DisciplineAreaCode"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Weight */
            weight: string;
        };
        /** DisciplineAreaSummaryResponse */
        DisciplineAreaSummaryResponse: {
            area: components["schemas"]["DisciplineAreaCode"];
            /** Name */
            name: string;
            /** Share */
            share: string;
        };
        /** DisciplineResponse */
        DisciplineResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Normalizedname */
            normalizedName: string;
            /** Areaweights */
            areaWeights: components["schemas"]["DisciplineAreaResponse"][];
            primaryArea: components["schemas"]["DisciplineAreaCode"];
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "NOT_FOUND" | "SOURCE_CONTRACT_ERROR" | "CONTRACT_ERROR" | "INTERNAL_ERROR";
        /** ErrorDetail */
        ErrorDetail: {
            /** Path */
            path: string;
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["ErrorDetail"][];
        };
        /** ProgramListResponse */
        ProgramListResponse: {
            /** Items */
            items: components["schemas"]["ProgramSummaryResponse"][];
        };
        /** ProgramResponse */
        ProgramResponse: {
            program: components["schemas"]["ProgramSummaryResponse"];
        };
        /** ProgramSummaryResponse */
        ProgramSummaryResponse: {
            /** Id */
            id: string;
            /** Directionid */
            directionId: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Educationyear */
            educationYear: number;
            /**
             * Studyplanurl
             * Format: uri
             */
            studyPlanUrl: string;
            /**
             * Sourceurl
             * Format: uri
             */
            sourceUrl: string;
        };
        /** WorkloadResponse */
        WorkloadResponse: {
            /** Semester */
            semester?: number | null;
            /** Hours */
            hours: number;
            /** Credits */
            credits?: string | null;
            /** Assessmenttypes */
            assessmentTypes?: components["schemas"]["AssessmentType"][] | null;
            /** Subjectgroup */
            subjectGroup?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_programs_programs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_program_programs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_curriculum_programs__id__curriculum_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurriculumResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_discipline_areas_discipline_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisciplineAreaCatalogResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_compare_get: {
        parameters: {
            query: {
                programIds: string;
                scope?: components["schemas"]["ComparisonScope"];
                semester?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
