import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const sourceFile = process.env.OPENAPI_FILE;
const sourceUrl = process.env.OPENAPI_URL ?? "http://127.0.0.1:8100/openapi.json";
const schema = sourceFile
  ? JSON.parse(await readFile(resolve(sourceFile), "utf8"))
  : await (await fetch(sourceUrl)).json();
const ast = await openapiTS(schema);
const output = `/* Generated by scripts/generate-api.mjs. Do not edit. */\n\n${astToString(ast)}`;
await writeFile(resolve("src/api/generated.openapi.ts"), output, "utf8");
console.log(`Generated src/api/generated.openapi.ts from ${sourceFile ?? sourceUrl}`);
