/* Generated by scripts/generate-api.mjs. Do not edit. */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_test_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_test_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Results */
        post: operations["results_api_test_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityCode
         * @enum {string}
         */
        ActivityCode: "analytical" | "software_creation" | "system_design" | "research" | "physical_engineering" | "communication" | "creative" | "business" | "data";
        /** AdaptiveAnswerPayload */
        AdaptiveAnswerPayload: {
            /** Questionid */
            questionId: string;
            /** Optionid */
            optionId: string;
            /** Firstdimension */
            firstDimension: string;
            /** Seconddimension */
            secondDimension: string;
        };
        /** AdaptiveDimensionResponse */
        AdaptiveDimensionResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "area" | "activity";
            /** Spread */
            spread: string;
            /** Significance */
            significance: string;
        };
        /** AdaptiveOptionResponse */
        AdaptiveOptionResponse: {
            /**
             * Id
             * @enum {string}
             */
            id: "more_first" | "balanced" | "more_second";
            /** Label */
            label: string;
            /** Description */
            description: string;
        };
        /** AdaptiveQuestionResponse */
        AdaptiveQuestionResponse: {
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /** Helpertext */
            helperText: string;
            firstDimension: components["schemas"]["AdaptiveDimensionResponse"];
            secondDimension: components["schemas"]["AdaptiveDimensionResponse"];
            /** Options */
            options: components["schemas"]["AdaptiveOptionResponse"][];
        };
        /** AdaptiveResponse */
        AdaptiveResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "skipped";
            /** Reason */
            reason?: string | null;
            /** Candidatecount */
            candidateCount: number;
            /** Topcandidatecount */
            topCandidateCount: number;
            question?: components["schemas"]["AdaptiveQuestionResponse"] | null;
        };
        /** AnswerOptionResponse */
        AnswerOptionResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Requiresintensity */
            requiresIntensity: boolean;
        };
        /** AnswerPayload */
        AnswerPayload: {
            /** Questionid */
            questionId: string;
            /** Optionid */
            optionId: string;
            /** Intensity */
            intensity?: number | string | null;
        };
        /**
         * AreaCode
         * @enum {string}
         */
        AreaCode: "mathematics_statistics" | "computer_science_data" | "physics_astronomy" | "chemistry_materials" | "biology_biotechnology" | "earth_environment" | "engineering_technology" | "architecture_construction" | "agriculture_veterinary" | "medicine_health" | "psychology_cognitive" | "society_social_sciences" | "economics_finance" | "business_management" | "law_policy_public_administration" | "languages_linguistics_literature" | "history_philosophy_humanities" | "art_design_media" | "education_pedagogy" | "sport_tourism_hospitality" | "safety_defense_transport" | "universal_interdisciplinary";
        /** BootstrapResponse */
        BootstrapResponse: {
            /**
             * Status
             * @constant
             */
            status: "ready";
            /** Service */
            service: string;
            /** Testversion */
            testVersion: string;
            /**
             * Catalogstatus
             * @constant
             */
            catalogStatus: "not_loaded";
            /**
             * Datasource
             * @constant
             */
            dataSource: "andromeda_http_api";
            /** Questions */
            questions: components["schemas"]["QuestionResponse"][];
            /** Totalbase */
            totalBase: number;
        };
        /** CatalogProgramResponse */
        CatalogProgramResponse: {
            /** Programid */
            programId: string;
            /** Programcode */
            programCode: string;
            /** Programname */
            programName: string;
            /**
             * Basis
             * @enum {string}
             */
            basis: "hours" | "credits";
            /** Totalhours */
            totalHours: number;
            /** Totalcredits */
            totalCredits: string;
            /** Totalworkload */
            totalWorkload: string;
            /** Areashare */
            areaShare: {
                [key: string]: string;
            };
            /** Subjectgroupshare */
            subjectGroupShare: {
                [key: string]: string;
            };
            /** Semesterdistribution */
            semesterDistribution: {
                [key: string]: string;
            };
            /** Activitysignals */
            activitySignals: {
                [key: string]: string;
            };
            /** Distinctivesubjects */
            distinctiveSubjects: components["schemas"]["DistinctiveSubjectResponse"][];
        };
        /** CatalogResponse */
        CatalogResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "partial" | "empty";
            /**
             * Datasource
             * @constant
             */
            dataSource: "andromeda_http_api";
            /** Programcount */
            programCount: number;
            /** Requestedprogramcount */
            requestedProgramCount: number;
            /** Failedprogramcount */
            failedProgramCount: number;
            /** Curriculumitemcount */
            curriculumItemCount: number;
            /** Programs */
            programs: components["schemas"]["CatalogProgramResponse"][];
            /** Note */
            note: string;
        };
        /** DistinctiveSubjectResponse */
        DistinctiveSubjectResponse: {
            /** Sourcename */
            sourceName: string;
            /** Normalizedname */
            normalizedName: string;
            primaryArea: components["schemas"]["AreaCode"];
            /** Workload */
            workload: string;
            /** Share */
            share: string;
            /** Rarity */
            rarity: string;
            /** Distinctiveness */
            distinctiveness: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: string;
            } | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /**
             * Datasource
             * @constant
             */
            dataSource: "andromeda_http_api";
        };
        /** MetricResponse */
        MetricResponse: {
            /**
             * Code
             * @enum {string}
             */
            code: "workload_readiness" | "career_fit" | "admission_fit";
            /** Label */
            label: string;
            /** Value */
            value?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "not_available" | "available";
        };
        /** PreviewResponse */
        PreviewResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "empty";
            /** Catalogprogramcount */
            catalogProgramCount: number;
            /** Profileconfidence */
            profileConfidence: string;
            adaptive?: components["schemas"]["AdaptiveResponse"] | null;
            progress: components["schemas"]["ProgressResponse"];
        };
        /** ProgressResponse */
        ProgressResponse: {
            /** Answeredbase */
            answeredBase: number;
            /** Totalbase */
            totalBase: number;
            /** Answeredadaptive */
            answeredAdaptive: number;
            /** Totalsteps */
            totalSteps: number;
        };
        /** QuestionResponse */
        QuestionResponse: {
            /** Id */
            id: string;
            /** Block */
            block: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Prompt */
            prompt: string;
            /** Helpertext */
            helperText: string;
            /** Required */
            required: boolean;
            /** Options */
            options: components["schemas"]["AnswerOptionResponse"][];
            /** Minselections */
            minSelections: number;
            /** Maxselections */
            maxSelections: number;
        };
        /** ReasonResponse */
        ReasonResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "positive" | "negative" | "distinctive" | "neutral";
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            area?: components["schemas"]["AreaCode"] | null;
            activity?: components["schemas"]["ActivityCode"] | null;
            /** Workload */
            workload: string;
            /** Share */
            share: string;
            /** Impact */
            impact: string;
            /**
             * Sourcenames
             * @default []
             */
            sourceNames: string[];
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Rank */
            rank: number;
            program: components["schemas"]["CatalogProgramResponse"];
            /** Contentfit */
            contentFit: number;
            breakdown: components["schemas"]["ScoreBreakdownResponse"];
            /** Reasons */
            reasons: components["schemas"]["ReasonResponse"][];
            /** Metrics */
            metrics: components["schemas"]["MetricResponse"][];
        };
        /** ResultsResponse */
        ResultsResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "empty";
            /**
             * Datasource
             * @constant
             */
            dataSource: "andromeda_http_api";
            /** Catalogprogramcount */
            catalogProgramCount: number;
            /** Profileconfidence */
            profileConfidence: string;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationResponse"][];
            /** Note */
            note: string;
        };
        /** ScoreBreakdownResponse */
        ScoreBreakdownResponse: {
            /** Subjectfit */
            subjectFit: string;
            /** Activityfit */
            activityFit: string;
            /** Distinctivefit */
            distinctiveFit: string;
            /** Antipenalty */
            antiPenalty: string;
            /** Rawcontentfit */
            rawContentFit: string;
        };
        /** TestAnswersRequest */
        TestAnswersRequest: {
            /** Answers */
            answers: components["schemas"]["AnswerPayload"][];
            /** Adaptiveanswers */
            adaptiveAnswers?: components["schemas"]["AdaptiveAnswerPayload"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bootstrap_api_test_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_api_test_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestAnswersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    results_api_test_results_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestAnswersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
